namespace Referly.Models;

public enum ReferralResult
{
    HUNTER_NOT_EXIST,
    JOB_SEARCH_DONT_EXIST,
    REFERRAL_CREATED_SUCCESSFULLY,
    REFERRAL_UPDATED_SUCCESSFULLY,
    ALREADY_REFFERED_FOR_THIS_JOB,
    PDF_NOT_FOUND,
    FILE_MUST_BE_A_PDF

}
